### ISSUE TITLE
pcall(terminateStayResident)

### ISSUE THREAD

**Issue by ddevault** [KnightOS/KnightOS#323] opened 2015-08-02 13:06 UTC
[wikipedia](https://en.wikipedia.org/wiki/Terminate_and_stay_resident_program)

We should have a syscall that removes the process but marks all of your memory as permanent rather than freeing it. This would allow you to register hooks/callbacks without using up resources.

How do we handle k-macros in this situation?

**Comment by SirCmpwn** [comment] 2015-08-02 13:06
Two possible solutions for k-macros:

* Run the code at least once before terminating so they all resolve
* Don't mix data with code, then introduce a syscall that resolves all k-macros for a given block of memory.

**Comment by thirtythreeforty** [comment] 2015-08-03 14:14
Why is a TSR better than simply having a long-running process?  TSRs are just a workaround for the lack of multitasking.  Also, allowing userland processes to leak memory past their death seems like a bad idea.

What would userland hook that would need such hooks?

**Comment by SirCmpwn** [comment] 2015-08-03 14:15
We've got a maximum of 16 concurrent processes.

I was thinking that this would be useful for #324.

**Comment by thirtythreeforty** [comment] 2015-08-03 14:21
Oh, I see.  That's a pretty small limit; it's down from what I remember (32 I think).

**Comment by SirCmpwn** [comment] 2015-08-03 19:32
Ah, it seems to be set to 32 right now, my bad.

**Comment by SirCmpwn** [comment] 2015-08-03 19:32
Still, they waste CPU time. I guess we could suspend it, but then we have important things showing up in task managers and such.

**Comment by thirtythreeforty** [comment] 2015-08-03 19:39
32 processes seems about right; even if there's a largeish number of daemons, the user won't hit a limit during reasonable use.  Daemons should definitely be suspended as they wait in the background, or for a registered callback.

As far as task managers, maybe the task manager shouldn't show all processes (*a la* the Windows task manager's Applications tab).

**Comment by SirCmpwn** [comment] 2015-08-03 20:35
Yeah, I'm not sure the best way to do that. Some processes would be seriously critical stuff. Imagine killing the compositor and suddenly you just have a blank screen until you reboot.

**Comment by SirCmpwn** [comment] 2015-08-03 20:35
Or worse, kill the compositor and it stays in memory, but the memory is marked as free and everything you do slowly corrupts it into strange and unexpected behavior long after you caused the problem.

**Comment by pixelherodev** [comment] 2018-10-20 20:09
Regarding TSRs and #324, wouldn't it be easier to just treat a TSR as a library? e.g. load it in as a library, spawn a thread that executes its entry point, set a "keep_in_memory" flag, and let the thread die normally?

We could use a load_tsr sycall that checks the KEXC header for an appropriate flag.

**Comment by SirCmpwn** [comment] 2018-10-20 20:10
meh, it's too early to design this anyway

**Comment by pixelherodev** [comment] 2020-10-14 05:27
One issue is almost solved: with #382, k-macros are no longer an issue.

This is still much too early to be worked on; this is purely to add relevant info to this thread as a note for the future.

**Comment by ddevault** [comment] 2020-10-14 12:27
TSRs are probably a bad idea for KnightOS.

**Comment by pixelherodev** [comment] 2020-10-14 12:39
What's the issue with them, given the previous arguments in their favor?

**Comment by ddevault** [comment] 2020-10-14 12:46
Well, we wanted to get rid of the static process table in favor of a dynamically allocated one, so process limits aren't an issue (and to be honest, 32 procs is not small enough to justify TSRs). Keeping an entry in the process list is helpful so that the user can manage and terminate processes themselves, rather than having a bunch of permanently allocated RAM unusable to them.

It'd be better to add some kind of advanced mode to the process list which shows system processes.

**Comment by pixelherodev** [comment] 2020-10-14 12:50
One option might be to have a flag to indicate that a process is only used for hooks and such; that could allow for better resource consumption without actually removing the process entry by reducing which information is stored. However, I don't think that's a good idea either.

I do agree with your logic there, though; I don't think we need TSRs.

**Closed by pixelherodev** 2020-10-14 12:50 UTC
Labels: assembly, feature, kernel, ★ ★ ☆
