### ISSUE TITLE
kcc generates empty asm output

### ISSUE THREAD

**Issue by ajcord** [KnightOS/KnightOS#360] opened 2017-05-22 21:08 UTC
When I run `make` on the template C project (created using `knightos init helloworld --template='c'`), everything runs fine until scas tries to link:
```
mkdir -p bin
kcc -V --verbose -I .knightos/include/ -I .knightos/ -I ./ -S --std-c99 main.c -o bin/main.asm
sdcc: Calling preprocessor...
+ cpp -nostdinc -Wall -std=c99 -I.knightos/include/ -I.knightos/ -I./ -D__SDCC_STACK_AUTO -D__SDCC_INT_LONG_REENT -D__SDCC_FLOAT_REENT -D__SDCC=3_4_1 -D__SDCC_REVISION=9072 -D__SDCC_z80 -D__STDC_NO_COMPLEX__ -D__STDC_NO_THREADS__ -D__STDC_NO_ATOMICS__ -D__STDC_NO_VLA__ -isystem /usr/local/bin/../share/sdcc/include/z80 -isystem /usr/local/share/sdcc/include/z80 -isystem /usr/local/bin/../share/sdcc/include -isystem /usr/local/share/sdcc/include  main.c @N@b?
sdcc: Generating code...
at 1: warning 190: ISO C forbids an empty source file
mkdir -p bin
scas -I .knightos/include/ -I .knightos/ -I ./ -c -o bin/main.o bin/main.asm
mkdir -p bin
scas -I .knightos/include/ -I .knightos/ -I ./ -c -o bin/crt0.o crt0.asm
mkdir -p bin/root/bin/
scas -fauto-relocation bin/crt0.o /Users/alex/Desktop/helloworld/.knightos/pkgroot/slib/c  bin/main.o -o bin/root/bin/helloworld
crt0.asm:15:0: error #5: Unknown symbol '_main'
    jp _main

make: *** [bin/root/bin/helloworld] Error 1
```

And here's the contents of bin/main.asm:
```
;--------------------------------------------------------
; File Created by SDCC : free open source ANSI-C Compiler
; Version 3.4.1 #9072 (May 21 2017) (Mac OS X x86_64)
; This file was generated Mon May 22 16:42:19 2017
;--------------------------------------------------------
	.module main
	.optsdcc -mz80
	
;--------------------------------------------------------
; Public variables in this module
;--------------------------------------------------------
;--------------------------------------------------------
; special function registers
;--------------------------------------------------------
	.area _RSEG (ABS)
	.org 0x0000
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _DATA
;--------------------------------------------------------
; ram data
;--------------------------------------------------------
	.area _INITIALIZED
;--------------------------------------------------------
; absolute external ram data
;--------------------------------------------------------
	.area _DABS (ABS)
;--------------------------------------------------------
; global & static initialisations
;--------------------------------------------------------
	.area _CODE
	.area _GSINIT
	.area _GSFINAL
	.area _GSINIT
;--------------------------------------------------------
; Home
;--------------------------------------------------------
	.area _CODE
	.area _CODE
;--------------------------------------------------------
; code
;--------------------------------------------------------
	.area _CODE
	.area _CODE
	.area _INITIALIZER
	.area _CABS (ABS)
```

So compilation is generating empty output. The warning says it's trying to compile an empty source file, but the preprocessor output looks correct. Wonder if it's an issue with the preprocessor's weird filenames?

**Comment by SirCmpwn** [comment] 2017-05-22 21:14
Dupe of #340

**Closed by SirCmpwn** 2017-05-22 21:14 UTC

**Comment by ajcord** [comment] 2017-05-22 21:19
Missed that, thanks
